name: docker

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Delete docs for old branches
        run: 
          - cd "$GITHUB_WORKSPACE/gh-pages"
          - find . -name .is_ref | while read line; do
              ref="$(dirname "$line")"
              ref="${ref:2}"
              if ! git rev-parse --verify -q "refs/remotes/origin/$ref" > /dev/null; then
                run rm -rf "$ref"
              fi
            done

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
        
      - name: Push latest images
        run: make push-latest
        if: github.ref == 'refs/heads/master'
