name: Main Workflow
'on':
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Build all images
        run: make -C repo all latest

      - name: Smoke test basic_example.py
        run: |
          cd repo/examples
          docker run --rm \
            --net host --pid host --userns host --privileged \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            -v $PWD:/examples -w /examples \
            ghcr.io/diselab/marvis ./basic_example.py

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Push latest images
        if: github.ref == 'refs/heads/master'
        run: make -C repo push-latest
